### ISSUE TITLE
Release mtail binaries

### ISSUE THREAD

**Issue by Lusitaniae** [google/mtail#117]
Can we make mtail binaries avaiable for upcoming releases?

We can make a similar process to the typical prometheus exporter with promu + CircleCI.

**Comment by jaqx0r** [comment]
mtail uses travis-ci.  Will that work?
Where should the binaries live?  How will versioning be managed?

**Comment by Lusitaniae** [comment]
Prometheus exporters actually use both usually.
Travis for testing but Circle for releasing.

The binaries will be available like this:
https://github.com/Lusitaniae/apache_exporter/releases
So each version will have its binaries.
When you release a new version on Github CircleCi will be notified and build and upload new binaries for that version.

They also build a docker image that will be hosted in Docker Hub and Quay.

**Comment by jarro2783** [comment]
I've been building the binaries myself by hacking `.travis.yml` if you want some inspiration: https://github.com/jarro2783/mtail

Travis does the deploy on a tag and uploads it to github using the tag name as the version.

**Comment by Lusitaniae** [comment]
Thanks for the suggestion @jarro2783, that might be enough.

Just a small issue, Travis is failing on my fork is there some environment variable I need to set?

**Comment by jarro2783** [comment]
I used `goxc` on my fork to build for multiple platforms. But other than than I didn't change anything about the build process from `master`.

**Comment by Lusitaniae** [comment]
I haven't made any changes yet but the build is failing,


```
0.42s$ make testrace

go test -v -timeout 60s -race ./... ./testdata

main.go:17:2: cannot find package "github.com/google/mtail/mtail" in any of:

	/home/travis/.gimme/versions/go1.8.linux.amd64/src/github.com/google/mtail/mtail (from $GOROOT)
```

https://travis-ci.org/Lusitaniae/mtail/jobs/294835472

I was wondering if there's some travis setting (provided outside the .travis.yml, maybe form the UI)

**Comment by jarro2783** [comment]
Oh it might be because there is an absolute import. I think I just disabled the tests for my build because of that.

**Comment by Lusitaniae** [comment]
@jaqx0r Any advise?

**Comment by jaqx0r** [comment]
Did you clone the repo into something in GOPATH?

**Comment by Lusitaniae** [comment]
I'm running the code in travis, should be already setup in the makefile no?
https://travis-ci.org/Lusitaniae/mtail/jobs/294835472

**Comment by jaqx0r** [comment]
We've got a circleci build up and running, and I'm very impressed with it.  Building packages regularly should be easier to add now.

**Comment by jaqx0r** [comment]
Lusitanae, I had a look at the apache exporter circle config but I can't figure out where the tarballs you linked to are created nor how they make their way back to Github's release page.

**Comment by Lusitaniae** [comment]
Hi Jamie,

i've made a quick demo on my account

```

    - run: sudo curl -L 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C $HOME
    - run: go build -o /tmp/mtail
    - store_artifacts:
        path: /tmp/mtail
        destination: mtail
    - run:  $HOME/github-release upload --user Lusitaniae --repo mtail --tag v3.0.0-release-test --name "mtail-linux-amd64" --file /tmp/mtail

```

To reproduce:
Create  a token here https://github.com/settings/tokens
Add to your Circle CI project environment variables in https://circleci.com/gh/google/mtail/edit#env-vars with key name GITHUB_TOKEN.
Create a release in Github, specify it in Circle.

In this way you don't have to use promu.

For the current setup of the prometheus exporters I'm using CircleCI v1 and  the configuration is quite different, but I hope you can use the help to elaborate your current config.
