### ISSUE TITLE
Only my application restart or shutdown write data!

### ISSUE THREAD

**Issue by huiqiangyang** [google/mtail#361]
问题现象：
只有在 应用 启动，重启，或者 关闭的时候， mtail 才会刷新数据。

怀疑是在文件停止写入的时候，mtail 才能够读取刷新数据到 Prometheus

grafana 监控看到的就是这样的:
![image](https://user-images.githubusercontent.com/13185035/101276718-c95aa280-37e9-11eb-8075-62fb18a0b7f8.png)

docker-compose.yml
```
  mtail:
    image: dylanmei/mtail
    container_name: jhipster6_mtail
    volumes:
      - /Users/user/myhome/jhipster6:/logs
      - ./mtail:/progs
    ports:
      - 3903:3903
    entrypoint:
      - mtail
      - --progs
      - /progs
      - --logs
      - /logs/*.log
```

```
# Copyright 2011 Google Inc. All Rights Reserved.
# This file is available under the Apache license.

counter lines_total

/$/ {
  lines_total++
}
```
