### ISSUE TITLE
I want to set to notify by e-mail when an arbitrary character string is recognized from the mtail monitoring log.

### ISSUE THREAD

**Issue by vdi-kakui** [google/mtail#423]
I want to create a mechanism to notify by email when mtail recognizes an arbitrary character string such as error in the following mtail program.

```
counter line counter error

/$/ {
  line++
  /error/ {
    error++
  }

}
```

But for that reason, I don't know how to write alert.rule to be read by prometheus.
I wrote the alert.rule I tried below, thank you.

```
groups:
- name: ap_error
  rules:
  - alert: Error
    expr: error_message > 1
    for: 1s
    labels:
      severity: warn
    annotations:
      summary: an error happened.
```
